### ISSUE TITLE
Icon on Windows

### ISSUE THREAD

**Issue by shankar2k** [eccentric-j/doom-icon#4]
I uploaded the png icon to an online Window ICO converter. Feel free to include it in the project. This icon looks great. Thanks!

[doom.zip](https://github.com/eccentric-j/doom-icon/files/5864658/doom.zip)

**Comment by jaidetree** [comment]
Thanks for creating this. I reorganized the icon folders and added it to https://github.com/eccentric-j/doom-icon/tree/7e1df84b334b76ee64853fa755f2e49d45db89be/abject-doom and added your name to the thanks section of the README.
